apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: nginx
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3 
  template:
    metadata:
      name: myapp      
      labels:
        app: myapp
        type: front-end        
    spec:
      containers:
        - name: nginx-controller        
          image: nginx
          ports:
            - containerPort: 80
