apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: nginx
  labels:
    app: myapp
    
spec:
  containers:
    - name: nginx-contianer
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
